### PR TITLE
Add typescript support

### PR DESCRIPTION
**Pull request by hmtylmz**
Add type definition file.

### CODE REVIEW

**Comment by stephg** [comment]
@hmtylmz would you like to update this?

Would be nice to see typescript support upstream...

**Comment by hmtylmz** [comment]
> @hmtylmz would you like to update this?
> 
> Would be nice to see typescript support upstream...

I resolved conflicts and pushed. You can merge now.

**Comment by puzrin** [comment]
Can it be better add types definitions to https://github.com/DefinitelyTyped/DefinitelyTyped?

**Comment by DanielHeath** [comment]
DefinitelyTyped is another option. It's typically used for projects who don't want to keep their own type definitions in-project. 

If you're willing to keep the type definitions up-to-date (eg when new options are added), having them in the project is better because you always get the right version. 

However, if you aren't interested in maintaining them yourself (or merging PRs to keep them updated), DefinitelyTyped is probably a better option.

**Comment by puzrin** [comment]
I don't use ts and can't provide support for it. Since DefinitelyTyped accepted PR, i think we can close this.

**Comment by denxorz** [comment]
If anybody lands here, install:
`npm i @types/pica --save-dev`

Then import:
`import Pica from 'pica';`

Then use:
```
const pica = Pica();
pica.resize(from, to);
```

**Pull request closed without merging**
