### PR TITLE
Specify the default value of `unsharpRadius`

### PR DESCRIPTION
**Pull request by YoranBrondsema**

### CODE REVIEW

**Comment by puzrin** [comment]
IMHO that will be confusing. Default is "not specified" and user should set it.

**Comment by YoranBrondsema** [comment]
I simply took the value that I could find in the code: https://github.com/nodeca/pica/blob/38b1f1e8fb28ebab39478ac9b974f16f3290e13e/index.js#L46.

**Comment by puzrin** [comment]
I know, but it's set to `0.0` due technical needs, this value is invalid if you need unsharp to work. If doc says, that variable has default value, user expect that value to be useable.

**Comment by YoranBrondsema** [comment]
I see. Alright, I now indicated the default value is unset (I still think it's better to indicate that rather than not say anything about its default value).

**Comment by puzrin** [comment]
No problem. Last one is acceptable. Could you merge this to single commit to keep history clear? (built-in github's squash moves existing texts to comments of final commit, i don't like this)

**Comment by YoranBrondsema** [comment]
Of course, should be good now!

**Comment by puzrin** [comment]
thanks!

**Pull request merged**
