### PR TITLE
The tiles should never be bigger than the image source. 

### LINKED ISSUE #61: SCRIPT5022: IndexSizeError in IE11 when using webworkers.
I sometimes get an error with IE11, it kind of depends on the image. I try to write a set of 8 images to another canvas. This is done after resizing the images with pica.  It works perfectly in chrome and firefox, but for IE11 it only works if i use WebGL.

The error is in resize_js_ww
``
    fromTileCtx.drawImage(from, tile.x, tile.y, tile.width, tile.height, 0, 0, tile.width, tile.height);
``

I'm having a hard time debugging this. It feel like it is trying to create an image larger than the canvas mabye? 

I tried to make a fiddle to show the problem, but i have a hard time isolating the problem.

### PR DESCRIPTION
**Pull request by bbrala**
This gives a SCRIPT5022: IndexSizeError in IE11. Fixed by checking if resulting size is not out of bounds.

Fixes #61

### CODE REVIEW

**Comment by puzrin** [comment]
I'm not sure that such fix is best of possible. Do you have an image that cause  bug in IE ?

@a-rodin could you check why output can exceed canvas size?

**Comment by bbrala** [comment]
@a-rodin there is some extra information in #61 with the sizes of the elements.

Really seems an issue of the ceil combined with a float scalefactor.

**Comment by a-rodin** [comment]
The problem in #61 is actually caused by floating point errors, ceil combined with a scalefactor as @bbrala said:
```javascript
> 36 / (36 / 500)
500.00000000000006
> Math.ceil(_)
501
``` 
I think that it is more straightforward to just fix floating point division instead of increasing complexity by handling all possible corner cases. 

It can be done by applying a function like this
```javascript
function fixPrecision (x) {
  var nearest = Math.round(x);
  return (Math.abs(x - nearest) < 1e-8) ? nearest : x;
}
```
to the arguments of `Math.floor` and `Math.ceil` in `createRegions` function.

**Comment by bbrala** [comment]
Thanks! I'll update the PR :)

For some reason i cannot build the dist tho, it failes building canvas.

**Comment by a-rodin** [comment]
@bbrala Thanks. But I've just fixed it myself :)

**Comment by bbrala** [comment]
Hehe, fair enough. I'll have a look if my code looks similar, i dont have much experience doing modules like this :)

**Comment by bbrala** [comment]
Well at least i did it correctly lol ;)

Also, for contributing you should document somewhere the canvas module needs the following command to be able to build:

OS | Command
----- | -----
OS X | `brew install pkg-config cairo libpng jpeg giflib`
Ubuntu | `sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++`
Fedora | `sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel`
Solaris | `pkgin install cairo pkg-config xproto renderproto kbproto xextproto`
Windows | [Instructions on our wiki](https://github.com/Automattic/node-canvas/wiki/Installation---Windows)

**Comment by puzrin** [comment]
Wouldn't it be better to write `almostFloor(x)` and `almostCeil(x)` instead of calling `floor(fix(x))` ?

`floor(fix(x))` looks a bit confusing in my eyes, because `fix` does not necessary "fix something broken".

**Pull request closed without merging**
